// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://czlqhjwubvrzmdwbdgwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bHFoand1YnZyem1kd2JkZ3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NjY2NDMsImV4cCI6MjA4NTQ0MjY0M30.AGs98UKX0LSn-tPLnp7sCjVgergt25hQTE-ux3iE2kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);